<h1>Please fill the custormer info</h1>
<?php echo $this->form ?>

<!-- 
Screen 1:
- Title [Drop Down Menu]
- Gender [Radio Buttons]
- First Name [Text - A-z only]
- Family Name [Text - A-z only]
- Email [Valid email only]
- Date of Birth [Date format]

Screen 2:
- Work Phone Number [Numbers - 0-9]
- Home Phone Number [Numbers - 0-9]
- Mobile Phone Number [Numbers - 0-9]
- Preferred contact nb [Radio Buttons]

Screen 3:

- Postcode [Numbers - 0-9 [4 digits only]]
- Suburb / Town [Text - A-z only]
- Street Address [Text - A-z 0-9 + special characters]
- State [Drop Down Menu]
-->